id: P58702582
initial_creation_type: ocr
source_metadata:
  volumes:
    77ad9e7c31864cd7ac3046818122560d:
      base_file: v001.txt
      image_group_id: I1PD95846
      title: བཅོམ་ལྡན་འདས་ལ་བསྟོད་པ་དཔལ་རྡོ་རྗེ་འཛིན་གྱི་དབྱངས།
      total_pages: 1539
      volume_number: 1
